# Generated by Django 5.2.1 on 2025-05-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=150)),
                ('categories', models.CharField(choices=[('mantenimiento', 'MANTENIMIENTO'), ('reparacion', 'REPARACION'), ('actividad', 'actividad')], max_length=15)),
                ('status', models.CharField(choices=[('finalizado', 'FINALIZADO'), ('pendiente', 'PENDIENTE'), ('asignado', 'ASIGNADO'), ('cancelado', 'CANCELADO')], max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True, max_length=500)),
                ('local', models.CharField(blank=True, max_length=10)),
                ('evidencias', models.FileField(blank=True, upload_to='')),
                ('detalle_final', models.TextField(blank=True)),
                ('asignado', models.CharField(blank=True, max_length=20)),
                ('realizado', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
