# Generated by Django 5.2.1 on 2025-05-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comercial_name', models.CharField(max_length=30)),
                ('sucursal_number', models.PositiveSmallIntegerField(default=1, unique=True)),
                ('ubicacion', models.URLField(blank=True)),
                ('start_date', models.DateField(blank=True)),
                ('purifier_info', models.TextField(blank=True, max_length=250)),
                ('no_ventanas', models.PositiveSmallIntegerField(default=1)),
                ('precio_fria', models.FloatField(default=7, max_length=5)),
                ('precio_tiempo', models.FloatField(default=14, max_length=5)),
            ],
        ),
    ]
